Velg fnr side
navikt/finn-kandidat pull request #14
Opened 2019-05-03 07:45 UTC by andrmos

2019-05-06 12:08 UTC, kjesvale requested changes

2019-05-06 12:08 UTC, kjesvale commented on src/App.tsx
>                      <Route exact path={AppRoute.OVERSIKT} component={Oversikt} />
Kan du endre enumsene til PascalCase? Som i `AppRoute.Oversikt`. Det er visstnok konvensjonen (ihvertfall i følge docs https://www.typescriptlang.org/docs/handbook/enums.html), så jeg har endret noen andre steder

2019-05-06 12:08 UTC, kjesvale commented on src/App.tsx
> +                    {/*<Redirect to={AppRoute.OVERSIKT} />*/}
Noen grunn til at du har fjerna redirect?

2019-05-06 12:08 UTC, kjesvale commented on src/pages/før-du-begynner/fnr-input/FnrInput.tsx
> +                feil={feilmelding ? { feilmelding: feilmelding } : undefined}
Kan fjerne `: feilmelding` siden variabelnavnet er det samme (`feilmelding ? { feilmelding }`)

2019-05-06 12:08 UTC, kjesvale commented on src/pages/før-du-begynner/infoboks/Veileder.tsx
> +                id="path-1"
Vi hadde litt problemer med `id`-er i SVG-er hos foreldrepenger. Med inline SVG-er vil nemlig disse ID-ene ofte krasje med andre ID-er siden Sketch bruker generiske navn som `path-1`, `circle` osv, og HTML-en blir semantisk ugyldig. Hvis SVG-en i tillegg bruker "masks", som i `<use>`-tags som refererer til `<defs>`-tags vil ikke disse fungere _i Firefox_ hvis det finnes ID-duplikater. Løsningen vår var å rydde opp i SVG-ene slik at de ikke brukte `defs`/`masks`, samt å fjerne alle ID-er siden disse ikke trengs lenger. En annen "løsning" kan være å prefixe alle ID-er med navnet på fila elns.

2019-05-06 13:41 UTC, andrmos commented on src/pages/før-du-begynner/infoboks/Veileder.tsx
> +                id="path-1"
Hmm synes det er litt kjipt med denne måten å bruke SVGer på. Man får SVGer fra Eivind, må paste dem inn i en nettside som gjør om til javascript, må legge denne koden inn i i en tsx komponent, og manuelt gå gjennom svg koden og fjerne id og eventuelle andre ting som ikke fungerer i diverse nettlesere.

Kan vi ikke bare ha SVG filene som egne filer og alt funker som det skal?

2019-05-06 13:50 UTC, andrmos commented on src/App.tsx
> +                    {/*<Redirect to={AppRoute.OVERSIKT} />*/}
Tok det bort under testing, tar tilbake!

2019-05-06 13:50 UTC, andrmos commented on src/App.tsx
>                      <Route exact path={AppRoute.OVERSIKT} component={Oversikt} />
Yessss

2019-05-06 14:09 UTC, kjesvale approved these changes

2019-05-07 07:01 UTC, LarsAndreasNav commented on src/utils/paths.ts
> +    FørDuBegynner = '/før-du-begynner',
Sikker på at det er OK med ø i url?

2019-05-07 07:13 UTC, Lars-Andreas reviewed
smooth kode ellers :taco:

2019-05-07 07:17 UTC, LarsAndreasNav commented on src/pages/før-du-begynner/FørDuBegynner.tsx
> +                <FnrInput fnr={fnr} setFnr={setFnr} feilmelding={feilmelding} />
Hva med å cleare feilmeldingen hver gang man endrer feltet?

2019-05-07 07:53 UTC, merged